title: Featherweight Web
description: Django and React Developer
author: Benjamin Dummer
github: https://github.com/featherweightweb
about: Django, React, and anything we consultant.
disqus_shortname: featherweightweb
google_analytics: UA-79153745-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-skype
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Github
      url: https://github.com/featherweightweb
    - text: XML Feed
      url: /feed.xml

url: "https://www.featherweightweb.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist